title: MaRS Team
name: Malaria Branch, CDC
email: your-email@example.com
description: Malaria Resistance Surveillance

parallax_image_one: assets/images/startup2.jpg # These are the images used for the parallax background
parallax_image_two: assets/images/startup2.jpg

project_one: MaRS Lab Protocol
project_one_description: Preparing full length genes Pf kelch 13 (k13), Pf chloroquine resistant transporter (crt), Pf multidrug resistant protein 1 (mdr1), Pf bifunctional dihydrofolate reductase-thymidylate synthase (dhfr), Pf dihydropteroate synthase (dhps) and mitochondrial genome amplicons for sequencing on the Illumina MiSeq system
project_one_url: https://github.com/CDCgov/MaRS/blob/master/lab_sop/MaRSsop.md
project_one_icon: location_on

project_two: MaRS Bioinformatics Pipeline
project_two_description: The Malaria Resistance Surveillance or MaRS analysis pipline, is an attempt at standardizing the workflow for identifying both known and new polymorhisms in P.falciparum genes associated with drug resistance.
project_two_url: https://github.com/CDCgov/MaRS
project_two_icon: photo_camera

project_three: nil
project_three_description: Describe your project!
project_three_url: https://github.com/jameshamann/jekyll-material-theme
project_three_icon: hotel


project_four: nil
project_four_description: Describe your project!
project_four_url: https://github.com/jameshamann/jekyll-material-theme
project_four_icon: restaurant

portfolio_heading: Projects
portfolio_type: cards

# Skill icons from https://konpa.github.io/devicon/

skills:
  - name: amazonwebservices
  - name: android
  - name: angularjs
  - name: apache
  - name: appcelerator
  - name: apple
  - name: atom
  - name: babel
  - name: backbonejs
  - name: bitbucket
  - name: bootstrap
  - name: bower
  - name: c
  - name: chrome
  - name: codeigniter
  - name: coffescript
  - name: confluence
  - name: cplusplus
  - name: csharp
  - name: css3
  - name: cucumber
  - name: d3js
  - name: debian
  - name: devicon
  - name: django
  - name: docker
  - name: doctrine
  - name: dot-net
  - name: drupal
  - name: erlang
  - name: facebook
  - name: firefox
  - name: foundation
  - name: gatling
  - name: gimp
  - name: git
  - name: github
  - name: gitlab
  - name: go
  - name: google
  - name: gradle
  - name: grunt
  - name: gulp
  - name: heroku
  - name: html5
  - name: ie10
  - name: illustrator
  - name: inkscape
  - name: itellij
  - name: java
  - name: jasmine
  - name: javascript
  - name: laravel
  - name: less
  - name: linux
  - name: meteor
  - name: mocha
  - name: mongodb
  - name: moodle
  - name: mysql
  - name: nginx
  - name: nodejs
  - name: nodewebkit
  - name: oracle
  - name: photoshop
  - name: php
  - name: phpstorm
  - name: protractor
  - name: postgresql
  - name: python
  - name: pycharm
  - name: rails
  - name: react
  - name: redhat
  - name: redis
  - name: ruby
  - name: rubymine
  - name: safari
  - name: sass
  - name: sequelize
  - name: slack
  - name: sourcetree
  - name: ssh
  - name: swift
  - name: symfony
  - name: tomcat
  - name: travis
  - name: trello
  - name: twitter
  - name: typescript
  - name: ubuntu
  - name: vim
  - name: visualstudio
  - name: vuejs
  - name: webpack
  - name: webstorm
  - name: windows8
  - name: wordpress
  - name: yii
  - name: zend

icon_size: 50 # font-size of icons in px
colored: colored # Leave blank for black and white icons

project_button: Github

github: https://github.com/jameshamann/jekyll-material-theme
medium: https://medium.com

baseurl: /MaRSWebsite # if your site is located at /blog or /home, enter it here, otherwise leave it empty
url: http://localhost:4000/ #the url of your site

google_analytics_tracking_id: # This looks something like UA-000000000-0 Head over to https://analytics.google.com/ to setup.

cookies_banner: none # The value "show" will show the cookies banner, the value "none" will hide the banner.

cookie_accept_message: Thanks!

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: false
highlighter: rouge

# theme: minima
permalink: pretty
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-minifier
